service: cs494a1
api_version: 1
runtime: php55
threadsafe: true

default_expiration: "1m"

handlers:
- url: /
  static_files: www/assignment_1_light.html
  upload: www/assignment_1_light.html

- url: /dark
  static_files: www/assignment_1_dark.html
  upload: www/assignment_1_dark.html

- url: /css
  static_dir: www/css

- url: /(.*\.(gif|png|jpb|html))$
  static_files: www/\1
  upload: www/(.*\.(gif|png|jpg|html)$)
