service: cs494a2
api_version: 1
runtime: php55
threadsafe: true

default_expiration: "1m"

handlers:
- url: /
  static_files: www/CS494_Assignment_2.html
  upload: www/CS494_Assignment_2.html

- url: /css
  static_dir: www/css

- url: /js
  static_dir: www/js

- url: /(.*\.txt)$
  static_files: www/txt/\1
  upload: www/txt/(.*\.txt$)
  

- url: /(.*\.(gif|png|jpb|html))$
  static_files: www/\1
  upload: www/(.*\.(gif|png|jpg|html)$)
